name: Olof Mogren
baseurl: /
permalink: /:categories/:year/:slug/
gems:
  - jekyll-feed

future: true
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: 'blog'
      type: posts
    values:
      permalink: /:categories/:year-:month-:day/:slug/
